// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zenebona.Models;

#nullable disable

namespace Zenebona.Migrations
{
    [DbContext(typeof(ZeneszamokContext))]
    partial class ZeneszamokContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Zenebona.Models.Eloado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Elo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nemzetiseg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Eloadok");
                });

            modelBuilder.Entity("Zenebona.Models.Kiado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("AlapitasEve")
                        .HasColumnType("smallint");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kiadok");
                });

            modelBuilder.Entity("Zenebona.Models.Zeneszam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EloadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Jogdijas")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("KiadoId")
                        .HasColumnType("int");

                    b.Property<double>("LejatszasiIdo")
                        .HasColumnType("double");

                    b.Property<int>("MegjelenesEve")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EloadoId");

                    b.HasIndex("KiadoId");

                    b.ToTable("Zeneszamok");
                });

            modelBuilder.Entity("Zenebona.Models.Zeneszam", b =>
                {
                    b.HasOne("Zenebona.Models.Eloado", "Eloado")
                        .WithMany("Zeneszamok")
                        .HasForeignKey("EloadoId");

                    b.HasOne("Zenebona.Models.Kiado", "Kiado")
                        .WithMany("Zeneszamok")
                        .HasForeignKey("KiadoId");

                    b.Navigation("Eloado");

                    b.Navigation("Kiado");
                });

            modelBuilder.Entity("Zenebona.Models.Eloado", b =>
                {
                    b.Navigation("Zeneszamok");
                });

            modelBuilder.Entity("Zenebona.Models.Kiado", b =>
                {
                    b.Navigation("Zeneszamok");
                });
#pragma warning restore 612, 618
        }
    }
}
