//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLogin_Host.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Felhasznalo", Namespace="http://schemas.datacontract.org/2004/07/TestLogin.Models")]
    [System.SerializableAttribute()]
    public partial class Felhasznalo : TestLogin_Host.ServiceReference1.Rekord {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AktivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HASHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfilKepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SALTField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aktiv {
            get {
                return this.AktivField;
            }
            set {
                if ((this.AktivField.Equals(value) != true)) {
                    this.AktivField = value;
                    this.RaisePropertyChanged("Aktiv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HASH {
            get {
                return this.HASHField;
            }
            set {
                if ((object.ReferenceEquals(this.HASHField, value) != true)) {
                    this.HASHField = value;
                    this.RaisePropertyChanged("HASH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Jog {
            get {
                return this.JogField;
            }
            set {
                if ((this.JogField.Equals(value) != true)) {
                    this.JogField = value;
                    this.RaisePropertyChanged("Jog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginNev {
            get {
                return this.LoginNevField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNevField, value) != true)) {
                    this.LoginNevField = value;
                    this.RaisePropertyChanged("LoginNev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfilKep {
            get {
                return this.ProfilKepField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilKepField, value) != true)) {
                    this.ProfilKepField = value;
                    this.RaisePropertyChanged("ProfilKep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SALT {
            get {
                return this.SALTField;
            }
            set {
                if ((object.ReferenceEquals(this.SALTField, value) != true)) {
                    this.SALTField = value;
                    this.RaisePropertyChanged("SALT");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rekord", Namespace="http://schemas.datacontract.org/2004/07/TestLogin.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestLogin_Host.ServiceReference1.Jogosultsag))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TestLogin_Host.ServiceReference1.Felhasznalo))]
    public partial class Rekord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jogosultsag", Namespace="http://schemas.datacontract.org/2004/07/TestLogin.Models")]
    [System.SerializableAttribute()]
    public partial class Jogosultsag : TestLogin_Host.ServiceReference1.Rekord {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeirasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SzintField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leiras {
            get {
                return this.LeirasField;
            }
            set {
                if ((object.ReferenceEquals(this.LeirasField, value) != true)) {
                    this.LeirasField = value;
                    this.RaisePropertyChanged("Leiras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Szint {
            get {
                return this.SzintField;
            }
            set {
                if ((this.SzintField.Equals(value) != true)) {
                    this.SzintField = value;
                    this.RaisePropertyChanged("Szint");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/FelhasznaloLista", ReplyAction="http://tempuri.org/IFelhasznalo/FelhasznaloListaResponse")]
        TestLogin_Host.ServiceReference1.Felhasznalo[] FelhasznaloLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/FelhasznaloLista", ReplyAction="http://tempuri.org/IFelhasznalo/FelhasznaloListaResponse")]
        System.Threading.Tasks.Task<TestLogin_Host.ServiceReference1.Felhasznalo[]> FelhasznaloListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/UjFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/UjFelhasznaloResponse")]
        string UjFelhasznalo(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/UjFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/UjFelhasznaloResponse")]
        System.Threading.Tasks.Task<string> UjFelhasznaloAsync(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/ModositFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/ModositFelhasznaloResponse")]
        string ModositFelhasznalo(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/ModositFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/ModositFelhasznaloResponse")]
        System.Threading.Tasks.Task<string> ModositFelhasznaloAsync(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/TorolFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/TorolFelhasznaloResponse")]
        string TorolFelhasznalo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFelhasznalo/TorolFelhasznalo", ReplyAction="http://tempuri.org/IFelhasznalo/TorolFelhasznaloResponse")]
        System.Threading.Tasks.Task<string> TorolFelhasznaloAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/JogosultsagLista", ReplyAction="http://tempuri.org/IJogosultsag/JogosultsagListaResponse")]
        TestLogin_Host.ServiceReference1.Jogosultsag[] JogosultsagLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/JogosultsagLista", ReplyAction="http://tempuri.org/IJogosultsag/JogosultsagListaResponse")]
        System.Threading.Tasks.Task<TestLogin_Host.ServiceReference1.Jogosultsag[]> JogosultsagListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/UjJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/UjJogosultsagResponse")]
        string UjJogosultsag(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/UjJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/UjJogosultsagResponse")]
        System.Threading.Tasks.Task<string> UjJogosultsagAsync(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/ModositJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/ModositJogosultsagResponse")]
        string ModositJogosultsag(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/ModositJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/ModositJogosultsagResponse")]
        System.Threading.Tasks.Task<string> ModositJogosultsagAsync(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/TorolJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/TorolJogosultsagResponse")]
        string TorolJogosultsag(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJogosultsag/TorolJogosultsag", ReplyAction="http://tempuri.org/IJogosultsag/TorolJogosultsagResponse")]
        System.Threading.Tasks.Task<string> TorolJogosultsagAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TestLogin_Host.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TestLogin_Host.ServiceReference1.IService1>, TestLogin_Host.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestLogin_Host.ServiceReference1.Felhasznalo[] FelhasznaloLista() {
            return base.Channel.FelhasznaloLista();
        }
        
        public System.Threading.Tasks.Task<TestLogin_Host.ServiceReference1.Felhasznalo[]> FelhasznaloListaAsync() {
            return base.Channel.FelhasznaloListaAsync();
        }
        
        public string UjFelhasznalo(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.UjFelhasznalo(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> UjFelhasznaloAsync(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.UjFelhasznaloAsync(felhasznalo);
        }
        
        public string ModositFelhasznalo(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.ModositFelhasznalo(felhasznalo);
        }
        
        public System.Threading.Tasks.Task<string> ModositFelhasznaloAsync(TestLogin_Host.ServiceReference1.Felhasznalo felhasznalo) {
            return base.Channel.ModositFelhasznaloAsync(felhasznalo);
        }
        
        public string TorolFelhasznalo(int id) {
            return base.Channel.TorolFelhasznalo(id);
        }
        
        public System.Threading.Tasks.Task<string> TorolFelhasznaloAsync(int id) {
            return base.Channel.TorolFelhasznaloAsync(id);
        }
        
        public TestLogin_Host.ServiceReference1.Jogosultsag[] JogosultsagLista() {
            return base.Channel.JogosultsagLista();
        }
        
        public System.Threading.Tasks.Task<TestLogin_Host.ServiceReference1.Jogosultsag[]> JogosultsagListaAsync() {
            return base.Channel.JogosultsagListaAsync();
        }
        
        public string UjJogosultsag(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.UjJogosultsag(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> UjJogosultsagAsync(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.UjJogosultsagAsync(jogosultsag);
        }
        
        public string ModositJogosultsag(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.ModositJogosultsag(jogosultsag);
        }
        
        public System.Threading.Tasks.Task<string> ModositJogosultsagAsync(TestLogin_Host.ServiceReference1.Jogosultsag jogosultsag) {
            return base.Channel.ModositJogosultsagAsync(jogosultsag);
        }
        
        public string TorolJogosultsag(int id) {
            return base.Channel.TorolJogosultsag(id);
        }
        
        public System.Threading.Tasks.Task<string> TorolJogosultsagAsync(int id) {
            return base.Channel.TorolJogosultsagAsync(id);
        }
    }
}
